version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

formats: all

build: 
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python: 
  # version: "3.7"
  install:
    - requirements: "requirements/docs.txt"
